# Form implementation generated from reading ui file 'GWinstek_plot.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(917, 888)
        self.plotWidgetRX = PlotWidget(parent=Form)
        self.plotWidgetRX.setGeometry(QtCore.QRect(20, 40, 881, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plotWidgetRX.setFont(font)
        self.plotWidgetRX.setObjectName("plotWidgetRX")
        self.label_14 = QtWidgets.QLabel(parent=Form)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=Form)
        self.label_15.setGeometry(QtCore.QRect(30, 440, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.plotWidgetPowRX = PlotWidget(parent=Form)
        self.plotWidgetPowRX.setGeometry(QtCore.QRect(20, 460, 881, 391))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plotWidgetPowRX.setFont(font)
        self.plotWidgetPowRX.setObjectName("plotWidgetPowRX")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_14.setText(_translate("Form", "График R-X"))
        self.label_15.setText(_translate("Form", "График мощности R-X"))
from pyqtgraph import PlotWidget
